daostack/arc.js

- package-lock.json
- package.json
- src/arc.ts
- src/reputation.ts
- src/token.ts
- src/utils.ts
- test/dao.spec.ts
- test/member.spec.ts
- test/operation.spec.ts
- test/proposal-claim-reward.spec.ts
- test/proposal-create.spec.ts
- test/proposal-execute.spec.ts
- test/proposal-stake.spec.ts
- test/proposal-vote.spec.ts
- test/proposal.spec.ts
- test/reputation.spec.ts
- test/reward.spec.ts
- test/stake.spec.ts
- test/token.spec.ts
- test/utils.ts
- test/vote.spec.ts
This is an attempt to get the contract addresses from the subgraph.
It works pretty well, excet that we need the addres of the Redeemer contract, which is not indexed, and therefore not available amount the indexed addresses.
For reference, try this query:
https://rinkeby.subgraph.daostack.io/subgraphs/graphql?query=%20%7B%0A%20%20%20%20%20%20%20%20%20%20subgraphs%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%20%20currentVersion%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20deployment%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20manifest%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20dataSources%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20 …
> get contract addresses from subgraph

- package.json
I think that it's useful to have this added to the published package because it makes it easier for projects to integrate this library.
Simply add this package as a dependency, and stand up the test environment via `docker-compose -f ./node_modules/@daostack/client/docker-compose.yml up graph-node`.
Additionally if there are other containers needed for the environment, they can use the docker-compose extends functionality: https://docs.docker.com/compose/extends/ .
I view this as being a best practice because it minimizes code duplication and provides a single source of truth for dependents.
> add docker to npm package

- package-lock.json
- package.json
- src/arc.ts
- src/operation.ts
- src/utils.ts
- test/operation.spec.ts
this PR addresses 3 different issues:
- remove metamask handling from the library (this should be done browser-side)
- add an extra state to the transaction.send() function `Sending`, which returns immediatly (without waiting for metamask to open), to fix https://github.com/daostack/alchemy/issues/512
- do not throw an error when getting options, which shoudl solve our top sentry issue: https://sentry.io/organizations/daostack-technologies/issues/1017580779/?environment=production&project=1419793&query=is%3Aunresolved
- bump version number
-
> remove metamask handling in arc.constructor

- package-lock.json
- package.json
- src/scheme.ts
- src/schemes/genericScheme.ts
- test/scheme.spec.ts
A quick hack to fix an issue in alchemy: adding generiscScheme information to the scheme.state().
> Generic scheme info

- package-lock.json
- package.json
- src/schemes/competition.ts
- test/proposal-competition.spec.ts
- test/utils.ts
- add an (async) isWinner and getPostion()
> competitions continued

- .travis.yml
- package-lock.json
- package.json
- src/index.ts
- src/proposal.ts
- src/schemes/competition.ts
- test/proposal-competition.spec.ts
- fix #368  
- fix #374 
- fix #350
> various fixes regarding competitions

- src/proposal.ts
@jellegerbrandy , can you please review the accuracy of the comments I am proposing here?
> comment stakes needed to preboost/unpreboost

- docker-compose.yml
- package-lock.json
- package.json
Gets in sync with test-env used by alchemy.  Should enable use of node v12 to install.  Also enables use of kovan (though I don't honestly know if that is necessary to accomodate in the client lib)
Resolves:  https://github.com/daostack/client/issues/436  (what remains of it)
Depends on https://github.com/daostack/test_env/pull/36
> upgrade to latest migration

- package-lock.json
- package.json
- src/arc.ts
- src/index.ts
- src/types.ts
- test/arc.spec.ts
- test/dao.spec.ts
- test/member.spec.ts
- test/proposal-create.spec.ts
- test/proposal-reward.spec.ts
- test/proposal.spec.ts
- test/scheme-reputationfromtoken.spec.ts
- test/stake.spec.ts
- test/token.spec.ts
- tslint.json
This PR adds support for "Custom Signers", which means a signer that's not provided through a web3 RPC provider. Here's what this looks like in practice:
```ts
const signer = new Wallet(
'0xe485d098507f54e7733a205420dfddbe58db035fa577fc294ebd14db90767a52',
new JsonRpcProvider('http://127.0.0.1:8545')
)
const arc = new Arc({
web3Provider: signer
// all other options
})
```
> Arc: Support Custom Signer + Fix Provider/Client Typings

- src/proposal.ts
- src/schemes/genericScheme.ts
- test/proposal-genericscheme.spec.ts
- test/proposal-ugenericscheme.spec.ts
Resolves: https://github.com/daostack/arc.js/issues/476
> add `value` to GenericScheme

- src/utils/operation.ts
@jellegerbrandy this makes the gas estimate logic identical to Arc.js 1.0. I found out that without multiplying by 2, estimating the gas limit for votes in GenesisProtocol are inconsistent and sometimes fail for some reason.
> Gas Limit Fix

- src/arc.ts
- test/arc.spec.ts
- test/utils.ts
Alias is needed for the case where a DAO has registered multiple schemes of the same type and dApps like Alchemy need a way to distinguish by name between them in their UI.
> include alias in IContractInfo

- src/arc.ts
- test/arc.spec.ts
- test/utils.ts
Merges https://github.com/daostack/arc.js/pull/492 from 1.0
> merge PR 492 from 1.0

- package-lock.json
- package.json
- src/plugins/fundingRequest/plugin.ts
- src/plugins/genericPlugin/plugin.ts
- src/plugins/genericPlugin/proposal.ts
- test/proposal-claim-reward.spec.ts
- test/proposal-genericscheme.spec.ts
Merges https://github.com/daostack/arc.js/pull/477 from 1.0
> merge PR 477 from 1.0

- package-lock.json
- package.json
- src/plugins/competition/proposal.ts
- src/plugins/contributionReward/proposal.ts
- src/plugins/contributionRewardExt/proposal.ts
- src/plugins/genericPlugin/proposal.ts
- src/plugins/proposal.ts
Resolves: https://github.com/daostack/arc.js/issues/516
This PR is necessary to solve issue https://github.com/daostack/alchemy/issues/1993 in Alchemy
> Add generic redeemRewards function ;  removed redundant code

- package-lock.json
- package.json
- src/plugins/joinAndQuit/plugin.ts
- src/utils/operation.ts
resolves: https://github.com/daostack/arc.js/issues/512
> fee.toString instead of fee.toNumber

- .travis.yml
- docker-compose.yml
- documentation/development.md
- package-lock.json
- package.json
- test-env-up.sh
- test/error.spec.ts
- test/proposal-competition.spec.ts
- test/utils.ts
bump version to 0.2.71
import subgraph-test-env as a workaround for test-env
> use migration 0.0.1-rc.44-v0 

- .travis.yml
- package-lock.json
- package.json
- src/schemes/competition.ts
- src/schemes/genericScheme.ts
- src/schemes/uGenericScheme.ts
- test/event.spec.ts
- test/proposal-competition.spec.ts
- test/proposal-genericscheme.spec.ts
Resolves: https://github.com/daostack/arc.js/issues/549
> Use BN for GenericScheme value

- docker-compose.yml
- package-lock.json
- package.json
- src/settings.ts
- test/proposal-join.spec.ts
resolves: https://github.com/daostack/arc.js/issues/561
> update migration to 0.1.2-rc.8-v0

- package-lock.json
- package.json
- src/graphnode.ts
resolves: https://github.com/daostack/alchemy/issues/2375
> Eliminate unnecessary web socket calls

- docker-compose.yml
- package-lock.json
- package.json
- src/index.ts
- src/scheme.ts
- src/schemes/base.ts
- src/schemes/ctl4rep.ts
- test/scheme-ctl4rep.spec.ts
support ContinousLocking4Reputation : `lock` , `extendLocking` ,`release` functions
> support ctl4rep

- package-lock.json
- package.json
- src/schemes/cl4rep.ts
- test/scheme-cl4rep.spec.ts
redeem for multiple locking ids . using redeemer helper
> cl4r : Redeem ids
