daostack/arc.js

- src/arc.ts
- src/dao.ts
- src/member.ts
- src/proposal.ts
- src/vote.ts
- test/member.spec.ts
- test/proposal.spec.ts
Merging this into `dev` branch
> Added get proposals for member + votes

- package-lock.json
- package.json
- src/arc.ts
- src/dao.ts
- src/proposal.ts
- src/utils.ts
- test/arc.spec.ts
- test/client.spec.ts
- test/proposal-create.spec.ts
- test/utils.ts
(not to merge yet; just sketching the approach for now)
> [WIP] write stuff to the blockchain

- package-lock.json
- package.json
- src/dao.ts
> Changed membercount to new subgraph var

- package-lock.json
- package.json
- src/arc.ts
- src/dao.ts
- src/member.ts
- src/operation.ts
- src/proposal.ts
- src/reputation.ts
- src/stake.ts
- src/token.ts
- src/types.ts
- src/utils.ts
- src/vote.ts
- test/arc.spec.ts
- test/dao.spec.ts
- test/member.spec.ts
- test/operation.spec.ts
- test/proposal-claim-reward.spec.ts
- test/proposal-create.spec.ts
- test/proposal-execute.spec.ts
- test/proposal-stake.spec.ts
- test/proposal-vote.spec.ts
- test/proposal.spec.ts
- test/reputation.spec.ts
- test/reward.spec.ts
- test/token.spec.ts
- test/utils.ts
- test/vote.spec.ts
> execute proposal

- documentation/example-session.md
- package-lock.json
- package.json
- src/arc.ts
- src/reputation.ts
- src/token.ts
- src/types.ts
- src/vote.ts
- test/arc.spec.ts
- test/client.spec.ts
- test/proposal-create.spec.ts
- test/utils.ts
Fixes #89 and  #92 , also sets version to 0.0.24
> Upgrade subgraph 

- package-lock.json
- package.json
- src/arc.ts
- src/member.ts
- src/operation.ts
- src/proposal.ts
- src/reputation.ts
- src/utils.ts
- test/arc.spec.ts
- test/client.spec.ts
- test/proposal-create.spec.ts
- test/reputation.spec.ts
- test/utils.ts
> Get account

- package-lock.json
- package.json
- src/dao.ts
- src/index.ts
- src/member.ts
- src/proposal.ts
- src/token.ts
- test/dao.spec.ts
- test/proposal-create.spec.ts
- test/proposal-execute.spec.ts
- test/proposal.spec.ts
- test/token.spec.ts
> [WIP] update subgraph dependency

- docker-compose.yml
- package-lock.json
- package.json
- test/proposal.spec.ts
Bump package version to 0.0.27
> Update migration to version 0.0.1-rc.11-v2

- package-lock.json
- package.json
- src/arc.ts
- src/index.ts
- src/proposal.ts
- src/stake.ts
- src/vote.ts
- test/arc.spec.ts
- test/member.spec.ts
- test/proposal-execute.spec.ts
- test/proposal-stake.spec.ts
- test/proposal-vote.spec.ts
- test/proposal.spec.ts
- test/stake.spec.ts
- test/vote.spec.ts
fixes #141, also updates version to 0.0.37
> proposaloutcome type

- package-lock.json
- package.json
- src/arc.ts
- src/index.ts
- src/operation.ts
- test/operation.spec.ts
- more aggressive fetching (less caching, but see #147 )
- bump version number to 0.0.41
- some refactor of package.json
- export operation states
- bump version to 0.0.42
> set default fetchPolicy to network-only

- .travis.yml
- package-lock.json
- package.json
- src/arc.ts
- src/operation.ts
- src/proposal.ts
- src/reputation.ts
- src/utils.ts
- src/vote.ts
- test/arc.spec.ts
- test/client.spec.ts
- test/dao.spec.ts
- test/member.spec.ts
- test/operation.spec.ts
- test/proposal-claim-reward.spec.ts
- test/proposal-create.spec.ts
- test/proposal-execute.spec.ts
- test/proposal-stake.spec.ts
- test/proposal-vote.spec.ts
- test/proposal.spec.ts
- test/reputation.spec.ts
- test/reward.spec.ts
- test/stake.spec.ts
- test/token.spec.ts
- test/utils.ts
- test/vote.spec.ts
this builds on PR #149, please review/merge that first
- add error handling for proposal.execute()
- add a arc.setAccount(..) helper function
- fix #147 
- unskip and fix some tests on votes
> add error handling for proposal.execute()

- docker-compose.yml
- package-lock.json
- package.json
- src/logger.ts
- src/proposal.ts
- test/proposal.spec.ts
- upgrade subgraph vo version 0.0.6
-
> upgrade subgraph deendency

- package-lock.json
- package.json
- src/proposal.ts
- src/utils.ts
- test/member.spec.ts
- test/proposal-execute.spec.ts
- test/proposal.spec.ts
- test/utils.ts
> implement upstakeneededtopreboost etc

- src/proposal.ts
This redeems the ContributionRewards but not not the GP rewards
> Allow for claimingRewards without a beneficiary

- package-lock.json
- package.json
- src/arc.ts
- src/index.ts
- src/proposal.ts
- src/queue.ts
- test/arc.spec.ts
- test/client.spec.ts
- test/dao.spec.ts
- test/queue.spec.ts
> get queue names from the contract addresses if we can

- src/proposal.ts
- test/proposal-schemeregistrar.spec.ts
- test/proposal.spec.ts
- test/utils.ts
this addresses issue #207. 
currently waiting for a resolution of https://github.com/daostack/subgraph/issues/223
> distinguish between add and edit schemeregistrar proposals

- .travis.yml
- package-lock.json
- package.json
- src/arc.ts
- src/operation.ts
- src/proposal.ts
- src/reputation.ts
- src/token.ts
- src/utils.ts
- test/member.spec.ts
- test/proposal-claim-reward.spec.ts
- test/proposal-create.spec.ts
- test/proposal-genericscheme.spec.ts
- test/proposal-schemeregistrar.spec.ts
- test/proposal-stake.spec.ts
- test/proposal-vote.spec.ts
- test/proposal.spec.ts
- test/utils.ts
> estimate gas a bit better

- package.json
- src/arc.ts
- src/dao.ts
- src/graphnode.ts
- src/member.ts
- src/operation.ts
- src/proposal.ts
- src/queue.ts
- src/reputation.ts
- src/reward.ts
- src/stake.ts
- src/token.ts
- src/utils.ts
- src/vote.ts
- test/arc.spec.ts
- test/dao.spec.ts
- test/proposal-claim-reward.spec.ts
- test/proposal-create.spec.ts
- test/proposal-execute.spec.ts
- test/proposal-genericscheme.spec.ts
- test/proposal-stake.spec.ts
- test/proposal.spec.ts
- test/queue.spec.ts
- test/reputation.spec.ts
- test/token.spec.ts
- test/utils.spec.ts
- test/utils.ts
> remove dependency on bn.js

- src/member.ts
- src/proposal.ts
- src/reputation.ts
- src/reward.ts
- src/stake.ts
- src/utils.ts
- src/vote.ts
- test/member.spec.ts
- test/proposal-claim-reward.spec.ts
- test/reputation.spec.ts
- test/reward.spec.ts
- tsconfig.json
fix for #217, need to test with alchemy
> have more restrictive type defs for query options

- package-lock.json
- package.json
- src/arc.ts
- test/utils.ts
> release 0.1.18

- package-lock.json
- package.json
- src/proposal.ts
- src/reward.ts
- src/schemes/contributionReward.ts
- test/reward.spec.ts
- contributionreward redemptions info, cf. #239
> [WIP] add info about contributionreward redemption

- package-lock.json
- package.json
- src/arc.ts
- src/proposal.ts
- src/reputation.ts
- src/schemes/genericScheme.ts
- src/token.ts
fixing, perhaps, https://github.com/daostack/alchemy/issues/834
needs a test (create > 100 proposal instances should do it)
> fix max-event-listeners error

- src/token.ts
- test/proposal.spec.ts
- test/token.spec.ts
> add an error handler for balanceOf non-existing tokens

- src/arc.ts
- src/graphnode.ts
- src/token.ts
- test/arc.spec.ts
- test/utils.ts
> add the option to have a 'read only' web3 provider

- .travis.yml
- README.md
- src/arc.ts
- test/arc.spec.ts
- test/utils.ts
- "fixes" sort of 265 (by rendering explicit what it does)
> remove arc.initialize method, replace by set/getContractInfos

- package-lock.json
- package.json
- src/dao.ts
- src/member.ts
- test/dao.spec.ts
> various improvements and tweaks

- src/graphnode.ts
- src/proposal.ts
- src/reward.ts
- src/scheme.ts
- src/stake.ts
- src/token.ts
- src/vote.ts
- test/cache.spec.ts
- test/proposal-claim-reward.spec.ts
- test/proposal-execute.spec.ts
- test/proposal-genericscheme.spec.ts
- test/proposal-reward.spec.ts
- test/proposal-schemeregistrar.spec.ts
- test/proposal-stake.spec.ts
- test/proposal-ugenericscheme.spec.ts
- test/proposal-vote.spec.ts
- test/proposal.spec.ts
- test/reward.spec.ts
- test/scheme.spec.ts
- test/utils.ts
- smarter cache handling for proposal votes
> caching improvements

- src/scheme.ts
- test/scheme.spec.ts
> [WIP] SchemeInfo 

- _config.yml
- docker-compose.yml
- package-lock.json
- package.json
- src/schemes/competition.ts
- src/utils.ts
- test/proposal-competition.spec.ts
- fix #357 (not the typeings, but the bug)
- fix #364 
- fix #368 
- fix #360 
- fix #351
> Subgraph 36 7

- src/arc.ts
- src/operation.ts
- src/schemes/base.ts
- src/schemes/competition.ts
- test/cache.spec.ts
- test/proposal-competition.spec.ts
> fix onlyAdmin

- docker-compose.yml
- documentation/development.md
- package-lock.json
- package.json
- src/graphnode.ts
- src/scheme.ts
- src/schemes/base.ts
- src/schemes/competition.ts
- src/utils.ts
- test/proposal-competition.spec.ts
Also refactor more scheme stuff to scheme/base to reduce duplicate code
And make sure boolean fields can be where queried
> Add isRegistered to schemes

- package-lock.json
- package.json
- src/member.ts
Needed to fix https://github.com/daostack/alchemy/issues/1593
> Add createdAt to member state

- scripts/copyABIsFromMigration.js
- src/arc.ts
> Remove dynamic require

- docker-compose.yml
- package-lock.json
- package.json
- src/dao.ts
- src/settings.ts
- test/dao.spec.ts
- test/proposal-joinAndQuit.spec.ts
- test/utils.ts
I have also created a kind of pre-release on the basis of this PR, even when tests are still failing..
> Upgrade to rc.20

- package-lock.json
- package.json
- src/plugins/pluginManager/plugin.ts
- src/plugins/pluginManager/proposal.ts
- test/proposal-pluginmanager.spec.ts
This PR is required to issue https://github.com/daostack/alchemy/issues/1893.
> Added function to decode data by plugin name

- src/plugins/proposal.ts
Merges changes from https://github.com/daostack/arc.js/pull/416
> merge PR 416 from 1.0

- docker-compose.yml
- package-lock.json
- package.json
- scripts/copyABIsFromMigration.js
- src/arc.ts
- src/settings.ts
resolves: https://github.com/daostack/arc.js/issues/510
> experimental 46

- package-lock.json
- package.json
- release.sh
- src/dao.ts
- test/dao.spec.ts
> support dao ethBalance 

- package.json
- src/plugins/pluginManager/plugin.ts
resolves: https://github.com/daostack/arc.js/issues/526
**NOTE:** This is a workaround
> Fetch correct package version for plugin manager

- package-lock.json
- package.json
> bump version to rc.54

- package-lock.json
- package.json
- src/settings.ts
Resolves: https://github.com/daostack/arc.js/issues/524
> add redeemer version

- package-lock.json
- package.json
- src/arc.ts
resolves: https://github.com/daostack/arc.js/issues/534
resolves: https://github.com/daostack/alchemy/issues/2097
> Loop with skips of 1000 to avoid hitting graph limit

- package-lock.json
- package.json
- src/plugins/join/plugin.ts
- src/utils/operation.ts
> update Join BN

- documentation/querying.md
- src/utils/graphnode.ts
- test/client.spec.ts
resolves: https://github.com/daostack/arc.js/issues/543
> Support poll interval to fetch from the graph

- documentation/querying.md
- package-lock.json
- package.json
- src/graphnode.ts
- test/client.spec.ts
resolves: https://github.com/daostack/arc.js/issues/543 for arc.js 1.0
> Support apollo polling from graph (1.0)

- docker-compose.yml
- package-lock.json
- package.json
- src/index.ts
- src/proposal.ts
- src/scheme.ts
- src/schemes/base.ts
- src/schemes/genericSchemeMultiCall.ts
- test/arc.spec.ts
- test/proposal-competition.spec.ts
resolves: https://github.com/daostack/arc.js/issues/552 for 1.0
> Support generic multi call

- src/plugins/plugin.ts
- src/plugins/pluginRegistrar/plugin.ts
- src/plugins/unknownPlugin.ts
resolves: https://github.com/daostack/arc.js/issues/555
> added isRegistered field to IPluginState

- package-lock.json
- package.json
- src/plugins/contributionReward/plugin.ts
- src/plugins/contributionRewardExt/plugin.ts
- src/plugins/fundingRequest/plugin.ts
- src/plugins/genericPlugin/plugin.ts
- src/plugins/join/plugin.ts
- src/plugins/pluginManager/plugin.ts
- src/plugins/pluginRegistrar/plugin.ts
- src/plugins/tokenTrade/plugin.ts
- test/proposal-pluginmanager.spec.ts
resolves: https://github.com/daostack/arc.js/issues/558
> Use string[] instead of number[] for voting params

- extract-abis.js
- package-lock.json
- package.json
resolves: https://github.com/daostack/arc.js/issues/567
> Update migration to 0.0.1-rc.52-v0

- src/proposal.ts
> schemeState name can be undefined
