daostack/arc.js

README.md
config/default.json
lib/config.js
lib/utils.js
test/config.js

Support overwriting defaults with environment variables in node.
https://trello.com/c/GlvMb6c7

Turn config object into a static singleton

---

README.md
lib/arc.d.ts
lib/dao.js
package-scripts.js
package.json

Converted references to "arc-js" to "arc.js".  Bumped version # to 15.

Arc-js to arc.js

---

lib/arc.d.ts
lib/arc.js
lib/avatarService.js
lib/contracts.js
lib/contracts/contributionreward.js
lib/contracts/genesisscheme.js
lib/contracts/vestingscheme.js
migrations/2_deploy_organization.js
test/contributionreward.js
test/dao.js
test/helpers.js
test/vestingscheme.js

Continues to address #24 by adding the VestingScheme wrapper.
Also cleans up the d.ts a little, and adds some stuff that got missed when creating the GenesisScheme wrapper.

Add vesting scheme wrapper

---

lib/arc.d.ts
lib/contracts.js
lib/contracts/daocreator.js
lib/contracts/globalconstraintregistrar.js
lib/dao.js
migrations/2_deploy_organization.js
package-lock.json
package-scripts.js
package.json
test/dao.js
test/helpers.js
test/vestingscheme.js
test/voteInOrganizationScheme.js

GenesisScheme => DaoCreator
remove "Log" from events
_globalconstraint => _globalConstraint in AddGlobalConstraint

upgrade to arc v28

---

README.md
lib/arc.d.ts
lib/contracts.js
lib/contracts/genesisProtocol.js
lib/dao.js
migrations/2_deploy_organization.js
package-lock.json
package-scripts.js
package.json
test/genesisProtocol.js
yarn.lock

- Adds genesis protocol handler.
- Adds scope to package 
Note this is as yet lacking some of the documentation.  But it would save me a bunch of time and tedious effort to finish that in the forthcoming typescript+automated-API documentation PRs, and until I have more information about how GenesisProtocol works -- I currently haven't a clue about some of it and would benefit from a conversation with someone more knowledgeable about it than me.

Add genesis protocol handler

---

config/default.json
lib/arc.d.ts
lib/contracts/contributionreward.js
lib/contracts/genesisProtocol.js
lib/contracts/vestingscheme.js
migrations/2_deploy_organization.js
package-lock.json
package-scripts.js
package.json
test/contributionreward.js
test/dao.js
test/genesisProtocol.js
test/globalconstraintregistrar.js
test/helpers.js
test/vestingscheme.js

Upgrade to Arc v31 GenesisProtocol and ContributionReward changes

Upgrade to Arc v31 GenesisProtocol and ContributionReward changes

---

.eslintrc.json
index.d.ts
lib/ExtendTruffleContract.ts
lib/contracts.ts
lib/contracts/absoluteVote.ts
lib/contracts/contributionreward.ts
lib/contracts/daocreator.ts
lib/contracts/voteInOrganizationScheme.ts
lib/dao.ts
lib/utils.ts
migrations/2_deploy_organization.js
package-lock.json
package-scripts.js
package.json
test/contributionreward.js
test/genesisProtocol.js
test/helpers.js
test/vestingscheme.js
test/voteInOrganizationScheme.js
tslint.json

Upgraded to Arc v34.
Cleaned up jslint packaging and config
Added functions to ContributionReward:
- redeemExternalToken
- redeemReputation
- redeemNativeToken
- redeemEther
- getDaoProposals
- getBeneficiaryRewards

ContributionReward enhancements

---

index.d.ts
lib/ExtendTruffleContract.ts
lib/contracts/absoluteVote.ts
lib/contracts/contributionreward.ts
lib/contracts/daocreator.ts
lib/contracts/genesisProtocol.ts
lib/contracts/globalconstraintregistrar.ts
lib/contracts/schemeregistrar.ts
lib/contracts/upgradescheme.ts
lib/contracts/vestingscheme.ts
lib/contracts/voteInOrganizationScheme.ts
lib/dao.ts
lib/test/contracts/testWrapper.ts
lib/utils.ts
test/genesisProtocol.js
test/globalconstraintregistrar.js
test/helpers.js
test/voteInOrganizationScheme.js
tslint.json

Addresses: #98 
Also:
- applies a modified tslint rule
- adds a `vote` method to `AbsoluteVote`

cease cloning the ExtendedTruffleContract

---

migrations/1_initial_migration.js
migrations/2_deploy_organization.js

This PR initially represents a cleanup of the Arc.js migration script.  I am presenting it also as a forum for everyone to review the script and to propose other changes in anticipation of an auditor's concerns.
Addresses: https://github.com/daostack/arc.js/issues/105
And at least in part: https://github.com/daostack/arc.js/issues/104

Cleanup migration script

---

custom_typings/system.d.ts
index.d.ts
package-lock.json
package-scripts.js
package.json
tsconfig.json
tslint.json

Add proposalId to ContributionProposal type

---

config/default.json
lib/contractWrapperBase.ts
lib/wrappers/genesisProtocol.ts
migrations/2_deploy_organization.js
package-lock.json
package.json
test/genesisProtocol.js

Addresses: https://github.com/daostack/arc.js/issues/151
See notes there

Really update to arc37

---

.babelrc
.travis.yml
docs/Migration.md
migrations/2_deploy_organization.js
package-lock.json
package-scripts.js
package.json

Work-around migration issues when running in the context of an application.

Build fixes

---

lib/wrappers/contributionreward.ts
test/contributionreward.js

Provide redeemable amounts in getBeneficiaryRewards

---

docs/Migration.md
lib/wrappers/daocreator.ts
package.json

ForgeOrgConfig typings corrections, new version 43

Forge org configtypings corrections

---

lib/contractWrapperBase.ts
lib/contractWrapperFactory.ts
lib/index.ts
lib/test/wrappers/testWrapper.ts
lib/wrapperService.ts
lib/wrappers/absoluteVote.ts
lib/wrappers/contributionreward.ts
lib/wrappers/daocreator.ts
lib/wrappers/genesisProtocol.ts
lib/wrappers/globalconstraintregistrar.ts
lib/wrappers/schemeregistrar.ts
lib/wrappers/tokenCapGC.ts
lib/wrappers/upgradescheme.ts
lib/wrappers/vestingscheme.ts
lib/wrappers/voteInOrganizationScheme.ts

- exposes ContractWrapperFactory class
- corrects misspelling of friendlyName property

typings changes

---

custom_typings/system.d.ts
lib/utils.ts
package-lock.json
package.json

fix access to globally-defined web3

---

docs/Daos.md
docs/Events.md
lib/contractWrapperBase.ts
lib/dao.ts
test/dao.js

Resolves: #40 
Resolves: #176 (remove duplicate events)

Get all daos

---

package-scripts.js

add --reset to migration command

---

lib/contractWrapperBase.ts
lib/dao.ts
test/dao.ts
test/helpers.ts

Resolves #203 
Resolves: #206 
- `DAO.getDaos` now invokes a callback on finding each new Dao
- renames test daos to be less distopian

DAO.getDaos invokes a callback on finding each new Dao

---

lib/wrappers/genesisProtocol.ts
package-lock.json
package.json

Get threshold returns big number

---

lib/migrations/2_deploy_organization.ts
lib/wrappers/genesisProtocol.ts
test/genesisProtocol.ts

This contains the new GP configuration parameters for the mainnet deploy.

Mainnet migration, new GP configuration

---

lib/wrappers/genesisProtocol.ts

revert the accidental commit of GP params changes

revert last commit

---

docs/Home.md
package-scripts.js
package.json

Resolves: #219 
- removes erroneous documentation that this script is required
- fixes the script itself

fix docs and fetchFromArc script

---

docs/Home.md
lib/commonTypes.ts
lib/test/wrappers/testWrapper.ts
lib/wrappers/contributionReward.ts
lib/wrappers/genesisProtocol.ts
lib/wrappers/globalConstraintRegistrar.ts
lib/wrappers/schemeRegistrar.ts
lib/wrappers/upgradeScheme.ts
lib/wrappers/vestingScheme.ts
lib/wrappers/voteInOrganizationScheme.ts
package.json
test/dao.ts

- remove unused parameter from `getDefaultPermissions`
- add `setParameters`
- changed comments on GP parameters

cleanup SchemeWrapper interface, getDefaultPermissions

---

lib/commonTypes.ts
lib/contractWrapperBase.ts
lib/test/wrappers/testWrapper.ts
lib/wrapperService.ts
lib/wrappers/contributionReward.ts
lib/wrappers/genesisProtocol.ts
lib/wrappers/globalConstraintRegistrar.ts
lib/wrappers/schemeRegistrar.ts
lib/wrappers/upgradeScheme.ts
lib/wrappers/vestingScheme.ts
lib/wrappers/voteInOrganizationScheme.ts
test/dao.ts
test/globalConstraintRegistrar.ts
test/utils.ts

Fixes bug in `getSchemePermissions` and adds a couple other minor enhancements.

fix getSchemePermissions

---

lib/loggingService.ts
package-lock.json
package.json
test/utils.ts

Fix crashes when stringifying objects having circular references.

handle logging circular json

---

custom_typings/web3.d.ts
lib/index.ts
lib/migrations/2_deploy_organization.ts
lib/utils.ts
package-scripts.js
package.json
test/genesisProtocol.ts
test/helpers.ts
test/utils.ts
truffle.js

This is what is to be deployed with the mainnet contracts, release v57.  Note that though the changes to deployment scripts reflect some advances in obtaining a mainnet deployment, they have yet not been shown to guarantee success.  That is a work in process.

Mainnet deploy

---

.gitignore
gasLimits.js
package-scripts.js
package-scripts/importArcGasLimit.js
package.json

Imports Arc gas limit from Arc, instead of hard-coding

Imports Arc gas limit from Arc, instead of hard-coding

---

docs/Transactions.md
mkdocs.yml

- fixes bug fix in docs build
- explains `error` when tx failed in Transactions.md

Fix mkdocs

---

lib/contractWrapperBase.ts
lib/dao.ts
lib/test/wrappers/testWrapper.ts
lib/transactionService.ts
lib/wrappers/absoluteVote.ts
lib/wrappers/contributionReward.ts
lib/wrappers/daoCreator.ts
lib/wrappers/genesisProtocol.ts
lib/wrappers/globalConstraintRegistrar.ts
lib/wrappers/schemeRegistrar.ts
lib/wrappers/tokenCapGC.ts
lib/wrappers/upgradeScheme.ts
lib/wrappers/vestingScheme.ts
lib/wrappers/voteInOrganizationScheme.ts
test/transactionService.ts

Fixes bug where the invocationKey did not have a constant value across the entire stack of events within a single invocation.

make invocationKey consistent

---

lib/contractWrapperBase.ts
package.json

don't sent tx if estimateGas fails

don't sent tx if estimateGas fails

---

lib/pubSubEventService.ts
lib/web3EventService.ts
test/transactionService.ts

- Fix the crash with unsubscribe and forEach
- Make unsubscribe be async to enable optional timeout

Fix the crash with unsubscribe and forEach

---

docs/Daos.md
docs/Home.md

Resolves: #265 
Resolves: #266
Fixes a couple bugs in the docs.

docs fixes

---

lib/index.ts
lib/migrations/2_deploy_schemes.ts
lib/scripts/createGenesisDao.ts
lib/wrappers/genesisProtocol.ts
package.json
truffle.js

- supply gas price to individual deployments
- make web3.eth.sign not synchronous
- expose Redeemer typings
- includes mainnet contract addresses

Migration tweaks

---

lib/wrappers/contributionReward.ts
lib/wrappers/genesisProtocol.ts
lib/wrappers/iIntVoteInterface.ts
package-lock.json
package.json
test/contributionReward.ts

- enable contribution proposals to be redeemable upon execution
- rename `ContributionReward.getVotableProposal` to `ContributionReward.getProposal`
**Breaking**
- rename `ContributionReward.getVotableProposal` to `ContributionReward.getProposal`

upgrade to arcv45, rename getVotableProposals

---

lib/wrappers/genesisProtocol.ts
package.json

await _validateVote

---

lib/scripts/createGenesisDao.ts
lib/transactionService.ts

fixes bugs in createGenesisDao against mainnet in the code that waits for the avatar to be accessible

fix bugs in createGenesisDao against mainnet

---

lib/wrappers/genesisProtocol.ts
lib/wrappers/intVoteInterface.ts
package-lock.json
package.json

- convert some GenesisProtocolProposals properties to numbers

convert some GenesisProtocolProposals properties to numbers

---

docs/Events.md
lib/dao.ts
lib/proposalService.ts
lib/web3EventService.ts
lib/wrappers/absoluteVote.ts
lib/wrappers/contributionReward.ts
lib/wrappers/genesisProtocol.ts
lib/wrappers/globalConstraintRegistrar.ts
lib/wrappers/redeemer.ts
lib/wrappers/schemeRegistrar.ts
lib/wrappers/upgradeScheme.ts
lib/wrappers/vestingScheme.ts
lib/wrappers/voteInOrganizationScheme.ts
package.json
test/web3EventService.ts

Adds the ability to set required depth on `watch` and `subscribe` on wrapper event and entity fetchers.

Add the ability to set required depth on watch and subscribe

---

lib/contractWrapperBase.ts
lib/web3EventService.ts
package.json
test/web3EventService.ts

- enable supplying depth  on `get`
- enable supplying depth on `EventFetcher`/`EntityFetcher` creation when auto-starting a watch
- fixes bug with depth on `watch` with `EntityFetcher`

more depth features, bug fixes

---

mkdocs.yml
package-lock.json
package.json

Bump version and update mkdocs.

Bump version

---

lib/wrappers/genesisProtocol.ts
package.json
test/genesisProtocol.ts

check for executed/closed in individual GP redeeming functions 

---

lib/configService.ts
test/utils.ts

Enable txDepthRequiredForConfirmation.live

---

docs/Configuration.md
lib/configService.ts
lib/index.ts
lib/loggingService.ts
test/utils.ts

update logLevel  on config changes

---

package-lock.json
package.json

upgrade to typescript 3.x

---

config/default.json
docs/Configuration.md
lib/index.ts
lib/utils.ts
test/config.ts
test/utils.ts

remove "http://" from provider Url
