daostack/arc.js

- package-lock.json
- package-scripts.js
- package.json
Addresses #35.
No more ES5 except for tests.
Also fixes reference to the truffle command after removing `migrateContracts.initialize`, and optimizes some package references.
This PR is needed to support a new PR for the Alchemy demo end-to-end functionality.
> no more ES5  except for tests

- lib/organization.js
- lib/utils.js
- package-lock.json
- package.json
- yarn.lock
Make sure to create our own Web3 object when we find it injected, this is a best practice and prepares us for when MetaMask will stop injecting web3
Don’t check for global web3 injection twice
Fix bug in Organization that wasn’t looking for web3 correctly
Make sure that every contract wrapper we create has its provider and default transaction arguments set correctly
Remove old testrpc package and duplicate @types/bignumber packages
Fixes https://github.com/daostack/Arc.js/issues/45
Trello: https://trello.com/c/HybXJwMR
> Clean up loading and usage of web3

- index.d.ts
- lib/ExtendTruffleContract.ts
- lib/arc.ts
- lib/contracts.ts
- lib/contracts/absoluteVote.ts
- lib/contracts/commonEventInterfaces.ts
- lib/contracts/contributionreward.ts
- lib/contracts/daocreator.ts
- lib/contracts/genesisProtocol.ts
- lib/contracts/globalconstraintregistrar.ts
- lib/contracts/schemeregistrar.ts
- lib/contracts/upgradescheme.ts
- lib/contracts/vestingscheme.ts
- lib/contracts/voteInOrganizationScheme.ts
- lib/dao.ts
- lib/utils.ts
- package-lock.json
- package.json
Addresses the first part of this:  https://github.com/daostack/arc.js/issues/41#issuecomment-364650691
In other words, we now have strong typings for the event argument properties.  There are no additional tests because 1) the existing tests adequately cover the modified architectural functionality, and 2) the tests are written in javascript and thus are not aware of typings.
I have tested that the typings work, in intellisense and in code compilation, in both Arc.js and Vanille.  My primary concern would be whether I have correctly defined the interfaces for the parameters returned by each Arc event.
We have not modified any of the wrapper function return-result classes (the second part of the comments referenced above).  To have done so would have been a _lot_ more work, and it is not …
> add event wrappers to all the contract wrappers

- test/contributionreward.js
- test/helpers.js
fix helper.js
need to return at async funcs. (test/helper.js).
> Fix contributionreward test

- README.md
- docs/GanacheDb.md
- package-scripts.js
- package.json
-runAsync command (npm start test.ganache.runAsync)  is not working as the cmd
- it is running an empty cmd 
>node node_modules/run-with-ganache/bin/run-with-ganache --ganache-cmd "${ganacheCommand}" " "`  
- till it will be fixed i guess it should be removed.
-not sure why it is needed in first place.
> Remove runAsync command.

- config/default.json
- index.d.ts
- lib/ExtendTruffleContract.ts
- lib/avatarService.ts
- lib/commonTypes.ts
- lib/contracts/commonEventInterfaces.ts
- lib/contracts/contributionreward.ts
- lib/contracts/genesisProtocol.ts
- lib/contracts/vestingscheme.ts
- lib/utils.ts
- package.json
- test/contributionreward.js
- test/genesisProtocol.js
- test/helpers.js
- test/vestingscheme.js
Addresses:
https://github.com/daostack/arc.js/issues/125
https://github.com/daostack/arc.js/issues/119
Threw in `VestingScheme.getAgreements`.
Regarding approval token transfers:  The added approvals only happen when `Config.get("autoApproveTokenTransfers")` is true, which is the default (so client apps can choose to disable it).
The approvals are happening in:
`ContributionReward.proposeContributionReward`
`GenesisProtocol.stake`
`VestingScheme.create`
> Approve staking transfer, added GenesisProtocol.getExecutedDaoProposals

- README.md
- config/default.json
- lib/utils.ts
- package.json
- test/config.js
Bump version for publishing new kovan deploy.  Also addresses https://github.com/daostack/arc.js/issues/83.
Potential breaking if someone is relying in their application on the modified Config parameters.
> bump version for kovan redeploy.  separate port from url in config

- README.md
- index.d.ts
- lib/ExtendTruffleContract.ts
- lib/contracts/absoluteVote.ts
- lib/contracts/contributionreward.ts
- lib/contracts/daocreator.ts
- lib/contracts/genesisProtocol.ts
- lib/contracts/globalconstraintregistrar.ts
- lib/contracts/schemeregistrar.ts
- lib/contracts/tokenCapGC.ts
- lib/contracts/upgradescheme.ts
- lib/contracts/vestingscheme.ts
- lib/contracts/voteInOrganizationScheme.ts
- lib/dao.ts
- lib/test/contracts/testWrapper.ts
- test/contributionreward.js
- test/dao.js
- test/genesisProtocol.js
- test/globalconstraintregistrar.js
- test/helpers.js
- test/schemeregistrar.js
- test/utils.js
- test/voteInOrganizationScheme.js
Address #72 and #92 
Adds the following methods to ExtendTruffleContract:
```
public async getParameters(paramsHash: Hash): Promise<any>;
public async getSchemeParametersHash(avatarAddress: Address): Promise<Hash>;
public async getParametersArray(paramsHash: Hash): Promise<Array<any>>;
```
And the following to Scheme wrappers:
```
public async getSchemeParameters(avatarAddress: Address): Promise<[any]>;
```
Where "[any]" is replaced by the type that defines an object interface containing the parameters for the scheme, like `StandardSchemeParams`.
One can obtain a scheme's voting machine address like this:
`const votingMachineAddress = (await scheme.getParameters(avatar)).votingMachineAddress`
**Breaking Changes**
* renames `votingMachine` to `votingMachineAddress` in parameter interfaces …
> new scheme parameters helper methods

- config/default.json
- index.d.ts
- lib/ExtendTruffleContract.ts
- lib/commonTypes.ts
- lib/contracts/contributionreward.ts
- lib/contracts/daocreator.ts
- lib/contracts/genesisProtocol.ts
- lib/contracts/globalconstraintregistrar.ts
- lib/contracts/schemeregistrar.ts
- lib/contracts/upgradescheme.ts
- lib/contracts/vestingscheme.ts
- lib/contracts/voteInOrganizationScheme.ts
- lib/dao.ts
- lib/test/contracts/testWrapper.ts
- lib/utils.ts
- migrations/2_deploy_organization.js
- package-lock.json
- package-scripts.js
- package.json
- test/dao.js
- test/genesisProtocol.js
- test/globalconstraintregistrar.js
- test/helpers.js
- test/schemeregistrar.js
- test/utils.js
- test/voteInOrganizationScheme.js
Addresses: #38 and #118 
- increased gas limit
- expanded permissions for SchemeRegistrar
- changed params for `SchemeRegistrar.proposeToAddOrModifyScheme` and `proposeToRemoveScheme`
- permissions are now defined in enums and passed around as such, rather than as strings
- sets gas limit in `DaoCreator.forgeOrg` when using a non-universal controller.
**Breaking**
- changed params for `SchemeRegistrar.proposeToAddOrModifyScheme` and `proposeToRemoveScheme`
- permissions are now defined in enums and passed around as such, rather than as strings (see `Dao.new`, `scheme.getDefaultPermissions`, DAO.getSchemes)
> upgrade to ArcV35

- lib/config.ts
Addresses: https://github.com/daostack/arc.js/issues/42
Have to prefix environment variable with "arcjs_" to override arc.js config settings.
The documentation change for this will be in [another PR where a new Configuration page exists](https://github.com/daostack/arc.js/pull/146).
This is a **breaking** change.
> Scope config settings

- docs/Home.md
- lib/dao.ts
- lib/wrapperService.ts
- mkdocs.yml
- package-scripts.js
- test/dao.js
- test/genesisProtocol.js
- test/globalconstraintregistrar.js
- test/helpers.js
- test/schemeregistrar.js
- test/vestingscheme.js
- test/wrapperService.js
Resolves #81 
Also:
- adds `WrapperServices.wrappersByAddress`
- removes `DAO.getContractWrapper`
Breaking:
- `name` is gone from `DaoSchemeInfo` and `DaoGlobalConstraintInfo`
- removes `DAO.getContractWrapper`
> Refactor getSchemes and getGlobalConstraints

- config/default.json
- lib/wrappers/contributionreward.ts
- lib/wrappers/daocreator.ts
- lib/wrappers/genesisProtocol.ts
- migrations/2_deploy_organization.js
- package-lock.json
- package.json
- test/genesisProtocol.js
- test/helpers.js
- test/upgradescheme.js
- test/wrapperService.js
Resolves #159
Resolves #163
Resolves #162
- Upgrades to Arc v38.
- switches Genesis DAO to the universal controller
Refer to: 
- #159 (comment)
- https://github.com/daostack/arc.js/pull/165 (previous closed PR on this)
**Breaking**: Converts number-typed values returned by `getParameters` and `getThreshold` from `BigNumber` to `number`
> Changes to GenesisProtocol parameters

- lib/index.ts
- lib/loggingService.ts
- lib/utils.ts
- lib/wrapperService.ts
- test/contributionreward.js
- test/helpers.js
- test/utils.js
- test/wrapperService.js
Resolves: #161 
- InitializeArc is renamed to InitializeArcJs
- InitializeArcJs detects when web3 is not connected
- InitializeArcJs now traps exceptions and throws a better message
- InitializeArcJs now accepts a filter of contract names to load
- LoggingService now accepts multiple loggers
- new `LoggingService.message` function for logging to multiple log levels
- change to tests so they run faster (don't call InitializeArcJs on every test)
**Note**: Documentation changes will be done in the [pending documentation PR](https://github.com/daostack/arc.js/pull/179).
**Breaking**
InitializeArc is renamed to InitializeArcJs
> Improvements to InitializeArc

- .gitignore
- config/default.json
- docs/Configuration.md
- docs/Migration.md
- lib/configService.ts
- lib/migrations/2_deploy_organization.ts
- lib/wrappers/daocreator.ts
- migrations/2_deploy_organization.js
- migrations/founders.json
- package-scripts.js
Resolves: #189
- Founders for networks other-than-ganache must be supplied via the `foundersConfigurationLocation` configuration setting.
- the Arc.js kovan founders are no longer stored in git
- configuration settings given in the OS environment must be pre-fixed by "arc_js".
**Question**
Should token and reputation amounts be given in Wei?
**Breaking**
Configuration settings given in the OS environment *must* be pre-fixed by "arc_js".  The code was allowing this to be optional, but we don't want to risk erroneously taking env variables from other contexts
> added foundersConfigurationLocation config setting

- lib/wrappers/genesisProtocol.ts
resolves: #196 
default is now 1, validated to be between 0 and 100
> proposingRepRewardConstB to 5

- lib/dao.ts
- lib/index.ts
- lib/migrations/2_deploy_organization.ts
- lib/utils.ts
- lib/wrappers/contributionReward.ts
- lib/wrappers/daoCreator.ts
- lib/wrappers/genesisProtocol.ts
- lib/wrappers/vestingScheme.ts
- migrations/2_deploy_organization.js
- package.json
- test/utils.ts
Replace all synchronous web3 calls with asynchronous ones, for compatibility with Web3 provider engines in the case that an application, like Alchemy, supplies the web3 instance. Possibly will improve performance with Metamask too.
> replace all synchronous web3 calls with asychronous ones

- gasLimits.js
- lib/index.ts
- lib/migrations/2_deploy_organization.ts
- lib/wrappers/genesisProtocol.ts
- package-lock.json
- package-scripts.js
- package.json
- test/dao.ts
- test/genesisProtocol.ts
- truffle.js
- upgrade to arc v42
- use truffle-hdwallet-provider for non-ganache migrations
- latest GP parameter defaults
**Notes**
- This doesn't include wrapper support for the new bounty features other than accounting for the new GP parameters.  That support will come in a separate PR.
- truffle-hdwallet-provider has issues described in slack [here](https://daostack.slack.com/archives/C95T9J92S/p1526653920000453)
> Upgrade to arc42 and truffle-hdwallet-provider

- config/default.json
- docs/Home.md
- lib/index.ts
- test/utils.ts
Recent changes to migration scripts in truffle.js would break applications' access to network defaults via `InitializeArcOptions.useNetworkDefaultsFor`.  This PR fixes that.
> restore network default values for applications

- custom_typings/web3.d.ts
- lib/avatarService.ts
- lib/utils.ts
- lib/wrappers/contributionReward.ts
- package-lock.json
- package.json
- test/contributionReward.ts
`getBeneficiaryRewards` now returns the amounts of ETH and external tokens that the Dao has available to pay out in the case they are redeemed.
> add available-to-redeem to getBeneficiaryRewards

- docs/Events.md
- lib/accountService.ts
- lib/avatarService.ts
- lib/dao.ts
- lib/index.ts
- lib/migrations/2_deploy_organization.ts
- lib/utils.ts
- lib/utilsInternal.ts
- mkdocs.yml
- test/accountService.ts
- test/helpers.ts
- test/utils.ts
Resolves: #237 
- adds AccountService that provides the ability to be notified whenever the current account changes.
- improves error handling when a DAO cannot be loaded (to enable apps to better handle the case when one switches to another chain while viewing a DAO that doesn't exist in the new chain.)
**Breaking**
- when a DAO cannot be loaded, either via `AvatarService` or `Dao.at`, we properly catch the exception and return `undefined`.  (The exceptions we were relying on before were not catchable, being treated as "unhandled promises".)
> Be notified when the account changes

- lib/utils.ts
- lib/wrapperService.ts
- package.json
- test/utils.ts
Adds the ability to confirm that a contract wrapper wraps what it purports to.
In the future we could perhaps do this on every call to `.at`.  But that would need to wait for PR #255 .
> added confirmContractType

- lib/wrappers/contributionReward.ts
- lib/wrappers/daoCreator.ts
- test/contributionReward.ts
- test/genesisProtocol.ts
- test/schemeRegistrar.ts
Resolves: #254 
**Breaking**:
- `SetSchemesConfig.SchemeConfig.additionalParams` goes away.  Additional parameters should be set in its place instead of under it.
> remove additionalParams from scheme spec

- lib/transactionService.ts
The bug causes too many TxTracking events to be issued in `GP.stake`, needed to do a full clone of eventContext.
> fix txTracking bug

- package-lock.json
- package.json
lock in version of ethjs-abi.  breaks transaction log decoding otherwise.
> lock in version of ethjs-abi.

- lib/transactionService.ts
- lib/utilsInternal.ts
- lib/web3EventService.ts
- lib/wrappers/genesisProtocol.ts
- lib/wrappers/redeemer.ts
- package-lock.json
- package.json
- test/genesisProtocol.ts
- test/redeemer.ts
This is straight 47, including the new `Redeemer` with no more event.
- `GenesisProtocolWrapper.getThreshold` no longer takes `proposalId` as a parameter
- the `Redeemer.Redeem` event has been removed
- `GenesisProtocolWrapper.stakeWithApproval` works in Metamask now
**Breaking**
- the `Redeemer.Redeem` event has been removed
- `genesisProtocol.getThreshold` no longer takes `proposalId` as a parameter
> Upgrade to Arc47

- lib/contractWrapperBase.ts
- lib/iContractWrapperBase.ts
- lib/test/wrappers/testWrapper.ts
- lib/wrappers/absoluteVote.ts
- lib/wrappers/contributionReward.ts
- lib/wrappers/daoCreator.ts
- lib/wrappers/genesisProtocol.ts
- lib/wrappers/globalConstraintRegistrar.ts
- lib/wrappers/schemeRegistrar.ts
- lib/wrappers/tokenCapGC.ts
- lib/wrappers/upgradeScheme.ts
- lib/wrappers/vestingScheme.ts
- lib/wrappers/voteInOrganizationScheme.ts
- test/absoluteVote.ts
- test/genesisProtocol.ts
Resolves: #313 
The main changes are in DaoCreator.ts.
- adds public `getParametersHash` to `ContractWrapperBase` and `IContractWrapperBase`
- makes `DaoCreator.setSchemes` forgo registering hash values if they have already been registered during the course of the call.
- makes `DaoCreator.setSchemes` await the mining of hash registrations
- fixes a bug in `DaoCreator.setSchemes` that caused the default voting machine to be overwritten when a scheme supplies it's own different voting machine.
> fixes and enhancements to DaoCreator.setSchemes

- lib/wrappers/genesisProtocol.ts
- test/genesisProtocol.ts
Resolves: #319 
Adds `GenesisProtocol.getBoostedProposalsCount`.  Returns the count of boosted proposals, accounting for those that have expired without being executed.
> Add GenesisProtocol.getBoostedProposalsCount

- config/default.json
- docs/Configuration.md
- lib/configService.ts
- lib/contractWrapperBase.ts
- lib/contractWrapperFactory.ts
- lib/iConfigService.ts
- lib/iContractWrapperBase.ts
- lib/index.ts
- lib/utils.ts
- package.json
- test/accountService.ts
- test/contributionReward.ts
- test/globalConstraintRegistrar.ts
- test/helpers.ts
- test/redeemer.ts
- test/schemeRegistrar.ts
- test/transactionService.ts
- test/utils.ts
- test/web3EventService.ts
- test/wrapperService.ts
Resolves: #324 
Cache contract wrappers obtained using the contract wrapper factory methods `.at` and `.new`.  The cache is local, it does not persist across application instances.
The feature is controlled by the `cacheContractWrappers` which is set to `false` by default.
> Cache contract wrappers

- lib/transactionService.ts
- package.json
This problem has been causing `DAO.new` to _sometimes_ report that "avatar address is not defined".
For some reason some nodes do not provide the `type` property on the TransactionReceipt object.  Arc.js was within reason interpreting the lack of this property to mean that the tx had not been mined.  However, the property was missing even when the tx *had* been mined.  So this appears to have been a blockchain node error.
The solution is to remove the check altogether.  It does not seem necessary to care about whether or not a tx has been mined in order to read its logs.
> `DAO.new` reports "avatar address is not defined"

- lib/accountService.ts
- lib/contractWrapperFactory.ts
- lib/index.ts
- lib/utils.ts
- lib/wrapperService.ts
- package-lock.json
- package.json
Resolves: #365
* uses the new MetaMask "ethereum" provider to instantiate web3, when available (see https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8)
* adds a function `Utils.getUserApprovalForAccounts` for popping up the MM approve-account-sharing dialog, returning whether the user approved.
* adds the ability for applications to be notified when the blockchain network id changes (via `InitializeArcOptions.watchForNetworkChanges`.
* adds ability to force `Utils.getWeb3` to re-instantiate the instance of web3 (such as when using a custom-provided web3 and the networkId has changed)
> Use new MetaMask "ethereum" provider

- lib/contractWrapperFactory.ts
- lib/utils.ts
- package-lock.json
- package.json
- test/absoluteVote.ts
When calling InitializeArcJs a second time with a new network id, the previously-fetched base truffle contract instances were not being uncached, so the contracts from the previous network were being used with the new network, causing failures.  Now they are being properly uncached.
**Breaking**: Also removes `Utils.getTruffleArtifactForContract` which was causing a warning in Webpack: 
> Critical dependency: the request of a dependency is an expression
This can be obtained from the factory for the contract `.ensureSolidityContract`
> fix contract truffle contract uncaching

- docs/index.md
> [docs] Fix typo in the script for starting Ganache

- lib/wrappers/genesisProtocol.ts
- package.json
Resolves: #373 
Only log the address from schemeInfo passed-into GP.getThresholdForSchemeAndCreator
> avoid MM problems when client passes-in object with synchronous web3 calls

- package-scripts.js
This fix is required mainly for a path which has a space (in directory name).
> Added quotes to path in migration command
